const subtitles = [
  "web developer.",
  "linux enthusiast.",
  "open source advocate.",
  "lifelong learner.",
  "student @ KTH.",
  "problem solver.",
  "passionate about technology.",
  "building for the web.",
  "exploring new tech.",
  "committed to quality code.",
  "collaborative team player.",
  "continuous improvement.",
  "curious by nature.",
  "focused on user experience.",
  "embracing challenges.",
  "seeking growth opportunities.",
  "dedicated to best practices.",
  "enjoying creative coding.",
  "interested in automation.",
  "striving for clean design.",
  "believer in open knowledge.",
  "always learning.",
  "sharing ideas.",
  "committed to accessibility.",
  "enthusiastic about innovation.",
  "making things better.",
  "solving real-world problems.",
  "writing maintainable code.",
  "valuing clear communication.",
  "inspired by technology.",
  "ready for new challenges.",
  "committed to lifelong learning.",
  "driven by curiosity.",
  "focused on results.",
  "adapting to new technologies.",
  "building scalable solutions.",
  "prioritizing security.",
  "writing clean, readable code.",
  "dedicated to continuous growth.",
  "enjoying teamwork.",
  "supporting open standards.",
  "interested in cloud computing.",
  "exploring data science.",
  "committed to documentation.",
  "embracing agile practices.",
  "seeking meaningful impact.",
  "valuing constructive feedback.",
  "motivated by challenges.",
  "striving for efficiency.",
  "passionate about problem solving.",
  "believer in collaboration.",
  "focused on usability.",
  "dedicated to quality assurance.",
  "interested in DevOps.",
  "building for accessibility.",
  "committed to ethical coding.",
  "open to new perspectives.",
  "valuing diversity in tech.",
  "inspired by creative solutions.",
  "aiming for excellence.",
  "enjoying lifelong discovery.",
  "motivated by innovation.",
  "prioritizing user needs.",
  "dedicated to professional growth.",
  "exploring full stack development.",
  "interested in AI and ML.",
  "building responsive interfaces.",
  "committed to sustainable code.",
  "valuing mentorship.",
  "embracing continuous delivery.",
  "focused on performance.",
  "driven by results.",
  "seeking collaborative environments.",
  "passionate about learning.",
  "committed to transparency.",
  "valuing open communication.",
  "interested in web standards.",
  "building inclusive products.",
  "dedicated to reliability.",
  "striving for simplicity.",
  "motivated by teamwork.",
  "focused on innovation.",
  "committed to personal development.",
  "exploring new frameworks.",
  "valuing user feedback.",
  "building secure applications.",
  "dedicated to code review.",
  "embracing new challenges.",
  "interested in automation tools.",
  "prioritizing maintainability.",
  "committed to best practices.",
  "valuing peer learning.",
  "focused on scalable design.",
  "motivated by real-world impact.",
  "building future-ready solutions.",
];
